#!/bin/bash

SUBLIMETEXT_CONF_DIR="$HOME/.config/sublime-text-3/Packages/User"
SUBLIMETEXT_PACKAGECONTROLE_URL="https://sublime.wbond.net/Package%20Control.sublime-package"

SUBLIMETEXT_CONF_KEYMAP="Default (Linux).sublime-keymap"
SUBLIMETEXT_CONF_SETTINGS="Preferences.sublime-settings"
SUBLIMETEXT_CONF_MARKDOWN="Markdown.sublime-settings"
SUBLIMETEXT_CONF_PHP="PHP.sublime-settings"
SUBLIMETEXT_CONF_PYTHON="Python.sublime-settings"
SUBLIMETEXT_CONF_PACKAGECONTROL="Package Control.sublime-settings"

# Backup config files
# -------------------------------------------------------------------
if [ -f "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_KEYMAP" ]; then
	mv "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_KEYMAP" "$DOTFILES_DIR/backup/$SUBLIMETEXT_CONF_KEYMAP.bak"
fi
if [ -f "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_SETTINGS" ]; then
	mv "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_SETTINGS" "$DOTFILES_DIR/backup/$SUBLIMETEXT_CONF_SETTINGS.bak"
fi
if [ -f "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_MARKDOWN" ]; then
	mv "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_MARKDOWN" "$DOTFILES_DIR/backup/$SUBLIMETEXT_CONF_MARKDOWN.bak"
fi
if [ -f "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_PHP" ]; then
	mv "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_PHP" "$DOTFILES_DIR/backup/$SUBLIMETEXT_CONF_PHP.bak"
fi
if [ -f "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_PYTHON" ]; then
	mv "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_PYTHON" "$DOTFILES_DIR/backup/$SUBLIMETEXT_CONF_PYTHON.bak"
fi
if [ -f "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_PACKAGECONTROL" ]; then
	mv "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_PACKAGECONTROL" "$DOTFILES_DIR/backup/$SUBLIMETEXT_CONF_PACKAGECONTROL.bak"
else
	echo "Download Package Control"
	wget -P "$SUBLIMETEXT_CONF_DIR" "$SUBLIMETEXT_PACKAGECONTROLE_URL"
fi

# Make symlinks
# -------------------------------------------------------------------
ln -s "$DOTFILES_SUBLIMETEXT/$SUBLIMETEXT_CONF_KEYMAP" "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_KEYMAP"
ln -s "$DOTFILES_SUBLIMETEXT/$SUBLIMETEXT_CONF_SETTINGS" "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_SETTINGS"
ln -s "$DOTFILES_SUBLIMETEXT/$SUBLIMETEXT_CONF_MARKDOWN" "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_MARKDOWN"
ln -s "$DOTFILES_SUBLIMETEXT/$SUBLIMETEXT_CONF_PHP" "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_PHP"
ln -s "$DOTFILES_SUBLIMETEXT/$SUBLIMETEXT_CONF_PYTHON" "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_PYTHON"
ln -s "$DOTFILES_SUBLIMETEXT/$SUBLIMETEXT_CONF_PACKAGECONTROL" "$SUBLIMETEXT_CONF_DIR/$SUBLIMETEXT_CONF_PACKAGECONTROL"
