#!/usr/bin/env bash

# Executed from Tmux hook session-created and window-linked


PROJECT_NAME="$1"
PROJECT_PATH="$2"

case "$PROJECT_NAME" in
	"main")
		;;

	# "adventofcode")
	# 	tmux split-window -v
	# 	tmux send-keys -t 1 'btop' C-m
	# 	tmux select-pane -t 1
	# 	;;

esac
