name: release
on:
  push:
    branch: default

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package
        shell: bash
        run: |
          mkdir -p build/_deps && mv textadept-build/* build/_deps && rm -r textadept-build
          cmake -S . -B build -D CMAKE_INSTALL_PREFIX=build/install
          cmake --build build --config Release -j
          cmake --install build --config Release
          git archive HEAD --prefix lsp/ | tar -xf -
          mv dkjson.lua ldoc ldoc.lua logging pl lsp
          zip -r lsp.zip lsp
      - name: Tag
        run: |
          git tag latest
          git push -f origin latest
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: latest
          allowUpdates: true
          body: |
            Latest automated build (ignore github-actions' release date)

            Note: this build may only be compatible with the latest release of Textadept
            (which may be an unstable release or a nightly build). If you are looking for a
            version of this module that is compatible with a specific version of Textadept,
            please download the "modules.zip" archive released alongside your version of Textadept.
          artifacts: lsp.zip
          token: ${{ secrets.GITHUB_TOKEN }}
  cleanup:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Remove older build artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 minute'
