#!/usr/bin/env bash

if [[ -n "$DISPLAY" ]]; then
	# Desktop

	if echo "$1" | cut -d'/' -f3 | grep -q -e youtube.com$ -e dailymotion.com -e vimeo.com$ -e spi0n.com$; then
		tmux split-window -d -l 10 -v "mpv $1"
	elif echo "$1" | grep -q -e jpg$ -e jpeg$ -e gif$ -e png$; then
		# Picture
		feh --auto-zoom -q "$1"
	else
		firefox "$1"
	fi
else
	# Server

	w3m "$1"
fi
