#!/usr/bin/env bash

# browser_text="/usr/bin/lynx -cfg=$HOME/.lynx/lynxrc -lss=$HOME/.lynx/lynx.lss"
browser_text="w3m"
browser_media="firefox"

if [[ -n "$DISPLAY" ]]; then
	# Desktop
	if echo "$1" | grep -e jpg$ -e jpeg$ -e gif$ -e png$; then
		# Picture
		$browser_media "$1"
	else
		$browser_text "$1"
	fi
else
	# Server
	$browser_text "$1"
fi
