set -g @theme "light"

# Window styles
set -g window-style 'bg=colour252'
set -g window-active-style 'bg=colour15'

# Pane styles
set -g pane-border-format "#{?pane_active,#[fg=black]#[bg=brightgreen],#[fg=black]#[bg=white]} #{pane_index} "

# Status bar
setw -g status-style fg=black,bg=white,default

setw -g window-status-current-style bg=white,fg=black,none
setw -g window-status-format "#{?window_activity_flag,#[fg=white]#[bg=brightblue],#[fg=black]#[bg=colour250]} #I #{?window_zoomed_flag,Z ,}#[bg=white]#[fg=black] #{=/22/...:window_name} #[default]"
setw -g window-status-current-format "#[fg=black]#[bg=brightgreen] #I #{?window_zoomed_flag,Z ,}#[bg=black]#[fg=white] #{=/22/...:window_name} #[default]"

setw -g status-left "#{?client_prefix,#[fg=black]#[bg=brightgreen],#[fg=black]#[bg=white]} #S #[default]        "
set -g status-right \
"#(~/.dotfiles/bin/tmux_vpn)\
#(~/.dotfiles/bin/tmux_battery -t)\
#(~/.dotfiles/bin/tmux_sound)\
#[bg=white]#[fg=black] #(ip -4 -o addr show scope global | awk '{print \$4}' | cut -d/ -f1 | head -n1) #[fg=black]#[bg=brightgreen] #H #[default] \
#[bg=white]#[fg=black] %Y-%m-%d #[fg=black]#[bg=brightgreen] %H:%M #[default]"
