set -g @theme "dark"

# Window styles
set -g window-style 'bg=colour233'
set -g window-active-style 'bg=colour16'

# Pane styles
set -g pane-border-format "#{?pane_active,#[fg=white]#[bg=green],#[fg=white]#[bg=black]} #{pane_index} "

# Status bar
setw -g status-style fg=white,bg=default,default

setw -g window-status-current-style bg=black,fg=white,none
setw -g window-status-format "#{?window_activity_flag,#[fg=white]#[bg=blue],#[fg=black]#[bg=green]} #I #{?window_zoomed_flag,Z ,}#[bg=black]#[fg=white] #{=/22/...:window_name} #[default]"
setw -g window-status-current-format "#[fg=white]#[bg=green] #I #{?window_zoomed_flag,Z ,}#[bg=white]#[fg=black] #{=/22/...:window_name} #[default]"

setw -g status-left "#{?client_prefix,#[fg=black]#[bg=green],#[bg=black]#[fg=cyan]} #S #[default]        "
setw -g status-right \
"#(~/.dotfiles/bin/tmux_vpn)\
#(~/.dotfiles/bin/tmux_battery -t)\
#(~/.dotfiles/bin/tmux_sound)\
#[bg=black]#[fg=white] #(ip -4 -o addr show scope global | awk '{print \$4}' | cut -d/ -f1 | head -n1) #[fg=black]#[bg=green] #H #[default] \
#[bg=black]#[fg=white] %Y-%m-%d #[fg=black]#[bg=green] %H:%M #[default]"
