#!/bin/bash
# This hook is run after every virtualenv is activated.

# Change prompt
# ----------------------------------------------------------------
PS1="[`basename \"$VIRTUAL_ENV\"`] $_OLD_VIRTUAL_PS1"

# Go to directory and update
# ----------------------------------------------------------------
VIRTUAL_ENV_ABSOLUTE="$PROJECT_HOME/$(basename $VIRTUAL_ENV)"

if [ -d "$VIRTUAL_ENV_ABSOLUTE" ]; then
	cd "$VIRTUAL_ENV_ABSOLUTE"

	# git update
	if [ "git rev-parse --git-dir > /dev/null 2>&1" ]; then
		git pull origin master
	fi
fi
