#!/usr/bin/env bash

if echo "$1" | cut -d'/' -f3 | grep -q -e youtube.com$ -e dailymotion.com -e vimeo.com$ ; then
	# Video
	if [[ -d "${HOME}/bin" ]]; then
		# Fix youtube-dl path with urlview
		export PATH="${HOME}/bin:$PATH"
	fi
	${HOME}/.dotfiles/bin/video "$1"
else
	if [[ -n "$DISPLAY" ]]; then
		# Browser Desktop
		if [[ -x $(which firefox) ]]; then
			"$(which firefox)" "$1"
		else
			"$BROWSER" "$1"
		fi
	else
		# Browser Server
		"$(which elinks)" "$1"
	fi
fi
