DOTFILES_PATH="$HOME/.dotfiles"

# Paths
# ------------------------------------------------------
if [[ -d "$DOTFILES_PATH/bin" ]] ; then
	export PATH="$DOTFILES_PATH/bin:$PATH"
fi

# Source files from dotfiles/bash folder
# ------------------------------------------------------
for file in "$DOTFILES_PATH/bash/"*; do
	if [[ -f "$file" ]]; then
		# Only if filename begin with underscore
		if [[ $(basename "$file") == "_"* ]]; then
			source "$file"
		fi
	fi
done

