
-- Disks bar
-- ----------------------------------------------------------------------------
-- local fsicon = wibox.widget.imagebox(beautiful.hdd)
-- fsbar = wibox.widget {
--	 forced_height	= 1,
--	 forced_width	 = 100,
--	 margins		  = 1,
--	 paddings		 = 1,
--	 ticks			= true,
--	 ticks_size	   = 6,
--	 max_value 		 = 100,
--	 value			= 0,
--	 color 			 = beautiful.success,
--	 background_color = beautiful.info,
--	 border_color	 = beautiful.info,
--	 widget		   = wibox.widget.progressbar
-- }
-- fs = lain.widget.fs({
--	 partition = "/",
--	 -- options = "--exclude-type=tmpfs",
--	 settings  = function()
--		 if tonumber(fs_now.used) < 90 then
--			 fsbar:set_color(beautiful.success)
--		 else
--			 fsbar:set_color(beautiful.error)
--		 end
--		 fsbar:set_value(fs_now.used)
--	 end
-- })
-- local fsbg = wibox.container.background(fsbar, beautiful.info, gears.shape.rectangle)
-- local myfswidget = wibox.container.margin(fsbg, 2, 7, 4, 4)
